### ISSUE TITLE
Why aren't you updating this mod to 1.16.4 when that version is more stable than 1.16.1?

### ISSUE THREAD

**Issue by vinnyg0621** [team-abnormals/upgrade-aquatic#222]
1.16.4 and 3 is more stable than 1.16.1. I saw you're still not updating any of your mods to that version. when are you gonna update it??

**Comment by bageldotjpg** [comment]
First of all, 1.16.4/3 is not really more stable than 1.16.1. They rewrote worldgen to use an experimental and unfinished system.
This is also why it is taking a while for us to update, because we have to re-do our worldgen.
Our updates are in progress. Be patient, modding is a hobby for us, not an obligation.
