### ISSUE TITLE
Massive amount of Thrashers

### ISSUE THREAD

**Issue by aaronhowser1** [team-abnormals/upgrade-aquatic#295]
![image](https://user-images.githubusercontent.com/15698722/131795046-9be3d73b-fa84-409d-a6ac-4c1338c62e7c.png)
![image](https://user-images.githubusercontent.com/15698722/131795073-830cb08b-7a58-4171-8f76-f5da5d9f006d.png)

Using the command `/execute as @e[type=upgrade_aquatic:thrasher] run say test` and counting the lines in the log, there's 48 Thrashers right here. That's _so many Thrashers_.

This is using `upgrade_aquatic-1.16.5-3.1.0`

**Comment by aaronhowser1** [comment]
There's also no other ocean life here, besides like 2 Frilled Sharks from Alex's Mobs

**Comment by bageldotjpg** [comment]
Change the rates of Thrashers in your config. Their spawn rates are designed around vanilla cave generation.

**Comment by turabian-luvr** [comment]
I see this issue is closed, but I'm having the same problem. This is after reducing the spawn weight of thrashers in the config from 90 to 10 and loading a completely new deep_frozen_ocean biome:

![2021-09-27_18 37 32](https://user-images.githubusercontent.com/54744184/134958108-fe2df895-bd09-4632-8545-da4fd50e87be.png)

The same test as op shows 44 thrashers and 16 great thrashers in the area.
